export const actionType={
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    TOGGLE_CART_DROPDOWN: 'TOGGLE_CART_DROPDOWN',
    ADD_ITEM: 'ADD_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    UPDATE_COLLECTION: 'UPDATE_COLLECTION'
};